  spring:
    profiles:
      default: dev
      group:
        "dev": ["secret-dev"]
        "prod": ["prod", "secret-prod"]
    application:
      name: miniproject
    cloud:
      aws:
        region:
          static: ap-northeast-2
        s3:
          bucket: miniproject-file-bucket
        cloudfront:
          domain: dyzr5x33xr922.cloudfront.net