spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME} # 환경 변수 사용
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul # KST(UTC+9)로 타임존 명시적 설정
        default_batch_fetch_size: 100
  data:
    redis:
      host: redis
      port: 6379
app:
  oauth2:
    redirect-uri: https://api.moodone.dev/oauth2/redirect
  cors:
    allowed-origins: https://moodone.dev, https://www.moodone.dev
admin:
  password: ${ADMIN_PASSWORD}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    com.mxxdone.miniproject: info
    org.springframework.security: WARN