spring:
  datasource:
    url: jdbc:postgresql://my-project-db.cv0468m20ioy.ap-northeast-2.rds.amazonaws.com:5432/miniproject
    username: ${DB_USERNAME} # 환경 변수 사용
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul # KST(UTC+9)로 타임존 명시적 설정
  data:
    redis:
      host: redis
      port: 6379
app:
  oauth2:
    redirect-uri: https://d1turob604d0fy.cloudfront.net/oauth2/redirect
  cors:
    allowed-origins: https://d1turob604d0fy.cloudfront.net
admin:
  password: ${ADMIN_PASSWORD}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
logging:
  level:
    com.mxxdone.miniproject: info
    org.springframework.security: WARN