  spring:
    profiles:
      default: dev
      group:
        "dev": ["secret-dev"]
        "prod": ["prod", "secret-prod"]
    application:
      name: miniproject
    cloud:
      aws:
        region:
          static: ap-northeast-2
        stack:
          auto: false
        s3:
          bucket: mxxdone-miniproject-bucket
        cloudfront:
          domain: d1turob604d0fy.cloudfront.net
    logging:
      level:
        org.hibernate.orm.jdbc.bind: trace